<?php

namespace App\Exceptions;

use App\Traits\ApiResponseTrait;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;
use Symfony\Component\HttpFoundation\Response;

class Handler extends ExceptionHandler
{
    use ApiResponseTrait;
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });

    }
    public function render($request, Throwable $exception)
    {
        if ($request-> expectsJson()){
            if ($exception instanceof  ModelNotFoundException){
                return $this->errorResponse(
                  'can not found data',
                  Response::HTTP_NOT_FOUND
                );
            }
            if ($exception instanceof NotFoundHttpException){
                return $this->errorResponse(
                  'can not found the URL',
                  Response::HTTP_NOT_FOUND
                );
            }
            if ($exception instanceof MethodNotAllowedHttpException){
                return $this->errorResponse(
                  $exception->getMessage(),
                  Response::HTTP_METHOD_NOT_ALLOWED
                );
            }
        }

        return parent::render($request, $exception); // TODO: Change the autogenerated stub
    }
}
